apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-3zm985
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3zm985
  namespace: my-nginx-3zm985
  labels:
    name: nginx-3zm985
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-3zm985
  template:
    metadata:
      namespace: my-nginx-3zm985
      labels:
        name: nginx-3zm985
    spec:
      containers:
      - name: nginx-3zm985
        image: nginx
        ports:
        - containerPort: 80

